language: android
jdk: oraclejdk8
#branches:
#  only:
#  - test-builds
#  - /^v([0-9]+)\.([0-9]+).*$/
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
addons:
  apt:
    sources: deadsnakes
    packages: python3.7
notifications:
  webhooks:
    urls:
      #- https://fathomless-fjord-24024.herokuapp.com/notify
      - https://travis-tg.herokuapp.com/u/897129600/force
    on_success: never # default: always
    #on_failure: always # default: always
    on_start:   always # default: never
    #on_cancel:  always # default: always
    #on_error:   always # default: always
  email: false
jobs:
  include:
    - stage: test-builds
      if: branch = test-builds
      env: BUILD_TYPE=test
    - stage: release
      if: branch != test-builds
      env: BUILD_TYPE=release

before_install: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1

before_script:
  - git fetch --unshallow

script: ./build.py mobile

after_success:
- TEXT="**$TRAVIS_BRANCH:**\`$TRAVIS_COMMIT\`"$'\n'"$TRAVIS_COMMIT_MESSAGE"$'\n'"$TRAVIS_BUILD_WEB_URL"
- APIPARAMS="-F parse_mode=Markdown -F disable_notification=true -F chat_id=$tgchat_id https://api.telegram.org/bot$tgtoken/sendDocument"
- curl -s -F document=@"build/mobile/IITC_Mobile-mobile.apk" -F caption="$TEXT" $APIPARAMS

before_deploy:
- sh bintray.json.sh > bintray.json

deploy:
  provider: bintray
  file: "bintray.json"
  user: #http://rkh.github.io/travis-encrypt/public/index.html
    secure: Pgyk7SPKuUX1Ohz69lSDIrxwODwzXhZ+FVuo6RG8z/RuNP7zW4yBLx7XMeX90V0EGK6vT8+8aZdlRwQgHb7S+jpSCQZbBQGQTG1n8YqWeXS6QvFdB2/aaeBjQNT4BzH1Cv9QJ2BSYtWkvD9ggIEK9aHqiZ1P8uz2ssesqP3eKhd410vFHJpKUM3YptXT+x1QxqO4m65CvKjS11b2AiFm7SQSwPekK7oB8RbdctRP2y+NFPZ2+dH7Nm+SiJFwiALYYU59eLU2l48r2ishkHm/BPoA4unicGcxaT9NbGsw9y0yLrRCqUDn2hIj3JLGg8ija7SUOiSyebhEoV9fXXS8Aj6GDZNdsgiwu0nJOtOOiK/tLwyE9spdCOATLJDTm7BwUPIwexCGwh9iSaCuTzicCP9QlugCPu8Q/G4tQn2uWsShwdYee34b73u2zr8tVNx4nol547REKBexfBsZS1HdU9Hmv9spK7YJQqYyB5vAsZ0hNk/6kBFHgH1r+XZfIfLem4npyyXv9ZO+dBo4jtNEcfu1a1C6DFdq4swOaz5FP+4TL2y5JcI4NgWM1Zjbm/XKoHcsnKwDDLDlZq3zoA5tUs8GllJD6mhmjuRglUptPrDAe82uCdfCZmggMhgjvFOoHqCBgm0sf50xxzgc6SHfAmsKfUwOTjxUuweEL0fLq4c=
  key:
    secure: HJ/AS9W3cSZq960Aec/lwze1Fy0KOdOZI0rdlfSLx1hEO3PzEaz+dVdiF8IyDiTN+VXbm20BqAa5nz03+Y/LXE3L6SfY2FJJXQfv7aZ++IvHmv/K6bpBFYCxqlCitJffv7zhr0yoLXCmjd5EpEvWImIR2gF8VNeUE+MVXl9wwO6UcddjjxvTxh9x54aYJZt6+uQyBqXv4IXqbdNRovployVnaxuuCgkKd7NXPA+Z119LWsm0FfJrc89R13xAyk0xbS1aglMeMBIpJMpsL0Li1yybs0WN0b6A34PRM1TsWozrFIoj7E8pv0EJpRqK9DZ2ZzuTnn9qJOYEPzwm+6r/VRv0LloHVb/T9O1cDDjC9M13xe8ov1iZuXZ5wSZqeXTH+RuM4kFZWRLXb95BShApE6pnkooFyK8p28op5NEW+PYHIPhEHR1Ht9WGhmxgJUm/dIsFyFSO6HPc74/Wp/SQGwg+trUZvK4J+W45OziGAcNmuo+hesLi5AFrF7fE9jiGnm9rrwg+nzRIW0HzRuwmU1+cKWiguITHkcvcdDcIqcNtfQHemya+UdD7MJwWZI8ZvNUw3f/5+VHRPFFAI6H3MrWIgM+7qbv8l0H4ouctgTYVE+zcONogrPe1H662IHMGWl8xvhnRkkB13e9QRUktAwDBcR5HXFd4umpzayWq8Z0=
  skip_cleanup: true
  on:
    all_branches: true
